# Configuração de financiamento para o GitHub - Vini Amaral
# Apoie o desenvolvimento de ferramentas Cloud-Native e Open Source

custom: [
  'https://www.asaas.com/c/2h5zwl883x3g3erc',
  'https://wa.me/5551981446019?text=Quero%20apoiar%20seus%20projetos'
]
